-- MySQL Script generated by MySQL Workbench
-- Sat Dec 24 022802 2022
-- Model New Model    Version 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ttf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ttf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ttf` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ttf` ;

-- -----------------------------------------------------
-- Table `ttf`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ttf`.`supervisor` (
  `Staff_ID` INT NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Phone_num` CHAR(10) NOT NULL,
  `College` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Staff_ID`),
  UNIQUE INDEX `Staff_ID_UNIQUE` (`Staff_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ttf`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ttf`.`student` (
  `University_ID` INT NOT NULL,
  `Staff_ID` INT NULL DEFAULT NULL,
  `Fullname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Phone_num` VARCHAR(10) NOT NULL,
  `College` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`University_ID`),
  UNIQUE INDEX `University_ID_UNIQUE` (`University_ID` ASC) VISIBLE,
  INDEX `Staff_ID_idx` (`Staff_ID` ASC) VISIBLE,
  CONSTRAINT `Staff_ID`
    FOREIGN KEY (`Staff_ID`)
    REFERENCES `ttf`.`supervisor` (`Staff_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ttf`.`training body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ttf`.`training body` (
  `TrainingBody_ID` INT NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Phone_num` VARCHAR(10) NOT NULL,
  `Website` VARCHAR(60) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Contact_Person` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TrainingBody_ID`),
  UNIQUE INDEX `TrainingBody_ID_UNIQUE` (`TrainingBody_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ttf`.`forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ttf`.`forms` (
  `Form_ID` INT NOT NULL,
  `FormName` VARCHAR(45) NOT NULL,
  `training body_TrainingBody_ID` INT NULL,
  `supervisor_Staff_ID` INT NULL,
  `student_University_ID` INT NULL,
  PRIMARY KEY (`Form_ID`),
  UNIQUE INDEX `Form_ID_UNIQUE` (`Form_ID` ASC) VISIBLE,
  INDEX `fk_forms_training body1_idx` (`training body_TrainingBody_ID` ASC) VISIBLE,
  INDEX `fk_forms_supervisor1_idx` (`supervisor_Staff_ID` ASC) VISIBLE,
  INDEX `fk_forms_student1_idx` (`student_University_ID` ASC) VISIBLE,
  CONSTRAINT `fk_forms_training body1`
    FOREIGN KEY (`training body_TrainingBody_ID`)
    REFERENCES `ttf`.`training body` (`TrainingBody_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forms_supervisor1`
    FOREIGN KEY (`supervisor_Staff_ID`)
    REFERENCES `ttf`.`supervisor` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forms_student1`
    FOREIGN KEY (`student_University_ID`)
    REFERENCES `ttf`.`student` (`University_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ttf`.`opportunity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ttf`.`opportunity` (
  `Opportunity_ID` INT NOT NULL,
  `OpportunityName` VARCHAR(45) NOT NULL,
  `training body_TrainingBody_ID` INT NULL,
  `student_University_ID` INT NULL,
  `supervisor_Staff_ID` INT NULL,
  UNIQUE INDEX `Opportunity_ID_UNIQUE` (`Opportunity_ID` ASC) VISIBLE,
  PRIMARY KEY (`Opportunity_ID`),
  INDEX `fk_opportunity_training body1_idx` (`training body_TrainingBody_ID` ASC) VISIBLE,
  INDEX `fk_opportunity_student1_idx` (`student_University_ID` ASC) VISIBLE,
  INDEX `fk_opportunity_supervisor1_idx` (`supervisor_Staff_ID` ASC) VISIBLE,
  CONSTRAINT `fk_opportunity_training body1`
    FOREIGN KEY (`training body_TrainingBody_ID`)
    REFERENCES `ttf`.`training body` (`TrainingBody_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opportunity_student1`
    FOREIGN KEY (`student_University_ID`)
    REFERENCES `ttf`.`student` (`University_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opportunity_supervisor1`
    FOREIGN KEY (`supervisor_Staff_ID`)
    REFERENCES `ttf`.`supervisor` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
