# Generated by Django 4.1.5 on 2023-01-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('University_ID', models.IntegerField()),
                ('College', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Staff_ID', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Department', models.CharField(max_length=50)),
                ('College', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Address', models.CharField(max_length=50)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=50)),
                ('Website', models.URLField(max_length=256)),
            ],
        ),
    ]
