# Generated by Django 4.1.5 on 2023-01-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('FormsImage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('UserName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Uni_id', models.CharField(max_length=10)),
                ('Fullname', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Department', models.CharField(max_length=80)),
                ('College', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('UserName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Department', models.CharField(max_length=80)),
                ('College', models.CharField(max_length=80)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBody',
            fields=[
                ('UserName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Website', models.URLField(max_length=256)),
                ('Address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opport_name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Training_tasks', models.CharField(max_length=256)),
                ('Gender', models.CharField(max_length=30)),
                ('Loaction', models.CharField(max_length=150)),
                ('vacancies', models.CharField(max_length=20)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.supervisor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
    ]
