# Generated by Django 4.1.5 on 2023-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college_id',
            new_name='University_ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='College',
            field=models.CharField(default='no college', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Phone_num',
            field=models.CharField(default='+966', max_length=20),
            preserve_default=False,
        ),
    ]
