# Generated by Django 4.1.5 on 2023-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_email_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Address', models.CharField(max_length=50)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=50)),
                ('Website', models.URLField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=35),
        ),
    ]
