# Generated by Django 4.1.5 on 2023-01-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_supervisor_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=35)),
                ('Address', models.CharField(max_length=50)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=50)),
                ('Website', models.URLField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='Address',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='Contact_Person',
            new_name='Department',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='Website',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='Staff_ID',
            field=models.CharField(default='00000', max_length=20),
            preserve_default=False,
        ),
    ]
