# Generated by Django 4.1.5 on 2023-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbody',
            name='Website',
            field=models.CharField(max_length=256),
        ),
    ]
