# Generated by Django 4.1.5 on 2023-02-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0002_alter_trainingbody_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='Supervisor',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='student',
        ),
    ]
