# Generated by Django 4.1.5 on 2023-02-03 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0003_remove_opportunity_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='FinishDate',
            field=models.CharField(default=datetime.datetime(2023, 2, 3, 23, 6, 13, 948972, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='StartDate',
            field=models.CharField(default=datetime.datetime(2023, 2, 3, 23, 6, 28, 652912, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
