# Generated by Django 4.1.5 on 2023-02-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0004_opportunity_finishdate_opportunity_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='FinishDate',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='StartDate',
        ),
    ]
