# Generated by Django 4.1.5 on 2023-02-03 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0005_remove_opportunity_finishdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='FinishDate',
            field=models.CharField(default=datetime.datetime(2023, 2, 3, 23, 9, 37, 706489, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='StartDate',
            field=models.CharField(default=datetime.datetime(2023, 2, 3, 23, 9, 41, 658854, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
