# Generated by Django 4.1.5 on 2023-02-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0007_supervisestudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='TrainingBody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.trainingbody'),
        ),
    ]
