# Generated by Django 4.1.5 on 2023-02-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0008_opportunity_trainingbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsItAccepted', models.CharField(max_length=10)),
                ('Opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.opportunity')),
                ('Supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.supervisor')),
                ('TrainingBody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.trainingbody')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.student')),
            ],
        ),
    ]
