# Generated by Django 4.1.5 on 2023-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0009_addopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addopportunity',
            name='notification',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
    ]
