# Generated by Django 4.1.5 on 2023-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0012_form9_form7_form6_form5_form4_form2'),
    ]

    operations = [
        migrations.AddField(
            model_name='form4',
            name='IsItCompleted',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form5',
            name='IsItCompleted',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form6',
            name='IsItCompleted',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form7',
            name='IsItCompleted',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form9',
            name='IsItCompleted',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
    ]
