# Generated by Django 4.1.5 on 2023-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0014_form2_isitcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='form7',
            name='SeriousTrainer',
            field=models.CharField(default='?', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form7',
            name='TimeGivenTraining',
            field=models.CharField(default='?', max_length=3),
            preserve_default=False,
        ),
    ]
