# Generated by Django 4.1.5 on 2023-02-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaibahTraining', '0015_form7_serioustrainer_form7_timegiventraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='form4',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.student'),
        ),
        migrations.AddField(
            model_name='form5',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.student'),
        ),
        migrations.AddField(
            model_name='form6',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.student'),
        ),
        migrations.AddField(
            model_name='form9',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaibahTraining.student'),
        ),
    ]
